listen_addresses = ['0.0.0.0:5353']
max_clients = 250
ipv4_servers = true
ipv6_servers = false
require_dnssec = false
require_nolog = true
require_nofilter = true
force_tcp = false
timeout = 2500
cert_refresh_delay = 30
## OPENDNS
fallback_resolver = "208.67.222.222:53"
block_ipv6 = true
cache = true
cache_size = 256
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_ttl = 60
[query_log]
file='/dev/stdout'
[nx_log]
[blacklist]
[ip_blacklist]
[sources]
  [static]
	[static.'securedns']
	stamp = 'sdns://AQcAAAAAAAAAEzE0Ni4xODUuMTY3LjQzOjUzNTMgs6WXaRRXWwSJ4Z-unEPmefryjFcYlwAxf3u0likfsJUcMi5kbnNjcnlwdC1jZXJ0LnNlY3VyZWRucy5ldQ'
